spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sarafan
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_cuntextual_creation: true

security:
  oauth2:
    client:
      clientId: ---
      clientSecret: ---
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile

    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
