spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sarafan
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    properties:
      hibernate.jdbc.lob.non_cuntextual_creation: true

